Proyecto_CoffeeRun/Models/categoria.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proyecto_CoffeeRun.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class categoria
    {
        public categoria()
        {
            this.producto = new HashSet<producto>();
        }
    
        public int Id { get; set; }
        public string nombre { get; set; }
    
        public virtual ICollection<producto> producto { get; set; }
    }
}

Proyecto_CoffeeRun/Controllers/CategoriaController.cs
using PagedList;
using Proyecto_CoffeeRun.Models;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;

namespace Proyecto_CoffeeRun.Controllers
{
    public class CategoriaController : Controller
    {
        public ModelCoffeeRunContainer db = new ModelCoffeeRunContainer();

        // GET: Productos
        public ActionResult Index(int page = 1, int pageSize = 9)
        {
            List<categoria> categorias = db.categoriaSet.ToList();
            PagedList<categoria> pageCategorias = new PagedList<categoria>(categorias, page, pageSize);

            return View(pageCategorias);
        }

        public ActionResult Crear()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Crear([Bind(Include = "Id,nombre")] categoria categoria)
        {
            if (ModelState.IsValid)
            {
                db.categoriaSet.Add(categoria);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(categoria);
        }

        public ActionResult Editar(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            categoria categoria = db.categoriaSet.Find(id);

            if (categoria == null)
            {
                return HttpNotFound();
            }

            return View(categoria);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Editar([Bind(Include = "Id,nombre")] categoria categoria)
        {
            if (ModelState.IsValid)
            {
                db.Entry(categoria).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(categoria);
        }

        public ActionResult Eliminar(int id)
        {
            categoria categoria = db.categoriaSet.Find(id);
            db.categoriaSet.Remove(categoria);
            db.SaveChanges();
            return RedirectToAction("Index");
        }
    }
}

Proyecto_CoffeeRun/Views/Categoria/Crear.cshtml
@model Proyecto_CoffeeRun.Models.categoria
@using Proyecto_CoffeeRun.Models;


@{
    ViewBag.Title = "Crear";
    Layout = "~/Views/Administrador/_AdmiMaster.cshtml";
}

@using (Html.BeginForm("Crear", "Categoria", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()
    <div class="row row-form">
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })

        <div class="col-md-6">

            <div class="form-group">
                @Html.LabelFor(model => model.nombre, "Nombre")
                @Html.EditorFor(model => model.nombre, new { htmlAttributes = new { @class = "form-control" } })
            </div>
          
            <input type="submit" class="btn btn-default" value="Crear" />
            @Html.ActionLink("Atras", "Index", null, new { @class = "btn btn-default" });

        </div>
       
    </div>
}

Proyecto_CoffeeRun/Views/Categoria/Editar.cshtml
@model Proyecto_CoffeeRun.Models.categoria
@using Proyecto_CoffeeRun.Models;


@{
    ViewBag.Title = "Editar";
    Layout = "~/Views/Administrador/_AdmiMaster.cshtml";
}

@using (Html.BeginForm("Editar", "Categoria", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()
    <div class="row row-form">
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)

        <div class="col-md-6">

            <div class="form-group">
                @Html.LabelFor(model => model.nombre, "Nombre")
                @Html.EditorFor(model => model.nombre, new { htmlAttributes = new { @class = "form-control" } })
            </div>
            <input type="submit" class="btn btn-default" value="Editar" />
            @Html.ActionLink("Atras", "Index", null, new { @class = "btn btn-default" });

        </div>
    </div>
}

Proyecto_CoffeeRun/Views/Categoria/Index.cshtml
@model PagedList.PagedList<Proyecto_CoffeeRun.Models.categoria>
@using PagedList.Mvc;

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Administrador/_AdmiMaster.cshtml";
}

<div class="row">
    <div class="col-md-12">
        <!-- Action Buttons -->
        <div class="pull-left">
            <h3>Categorias</h3>
        </div>
        <div class="pull-right">
            @Html.ActionLink("Crear", "Crear", null, htmlAttributes: new { @class = "btn btn-grey" })
        </div>
    </div>
</div>
<div class="row">
    <div class="col-md-12">
        <!-- Shopping Cart Items -->
        <table class="shopping-cart">
            <!-- Shopping Cart Item -->
            @foreach (var item in Model)
            {
                <tr>
                    <!-- Shopping Cart Item Description & Features -->
                    <td>
                        <div class="cart-item-title">@Html.DisplayFor(modelItem => item.nombre)</div>
                       
                    </td>
                    <td class="actions">
                        @Html.ActionLink(" ", "Editar", new { id = item.Id }, htmlAttributes: new { @class = "glyphicon glyphicon-pencil" })
                        @Html.ActionLink(" ", "Eliminar", new { id = item.Id }, htmlAttributes: new { @class = "glyphicon glyphicon-trash", onclick = "return confirm('¿Está seguro de eliminar la categoria?');" })
                    </td>
                </tr>
            }

        </table>
        <!-- End Shopping Cart Items -->
        @Html.PagedListPager(Model, page => Url.Action("Index", new { page, pageSize = Model.PageSize, ViewBag.categoria }), new PagedListRenderOptions { ContainerDivClasses = new[] { "pagination-wrapper" }, UlElementClasses = new[] { "pagination pagination-lg" } })
    </div>
</div>