Proyecto_CoffeeRun/Models/producto.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proyecto_CoffeeRun.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class producto
    {
        public producto()
        {
            this.categoria = new HashSet<categoria>();
        }
    
        public int id { get; set; }
        public string nombre { get; set; }
        public string descripcion { get; set; }
        public int precio { get; set; }
        public string tipo { get; set; }
        public string imagen { get; set; }
    
        public virtual ICollection<categoria> categoria { get; set; }
    }
}

Proyecto_CoffeeRun/Controllers/ProductoController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Proyecto_CoffeeRun;
using Proyecto_CoffeeRun.Models;
using System.Data.Entity;
using System.Data;
using System.Net;
using PagedList;
using System.IO;

namespace Proyecto_CoffeeRun.Controllers
{
    public class ProductoController : Controller
    {
        public ModelCoffeeRunContainer db = new ModelCoffeeRunContainer();

        // GET: Productos
        public ActionResult Index(int page = 1, int pageSize = 9)
        {
            List<producto> productos = db.productoSet.ToList();
            PagedList<producto> pageProductos = new PagedList<producto>(productos, page, pageSize);

            return View(pageProductos);
        }

        public ActionResult Crear()
        {
            List<categoria> categorias = db.categoriaSet.ToList<categoria>();
            ViewBag.categorias = new MultiSelectList(categorias, "Id", "nombre", null);
            categorias.Insert(0, new categoria { Id = -1, nombre = "Ninguna" });

            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Crear([Bind(Include = "id,nombre,descripcion,precio,tipo,imagen")] producto producto, FormCollection form)
        {
            if (!form["Categorias"].Split(',')[0].Equals("-1"))
            foreach (string i in form["Categorias"].Split(','))
            {
                Int32 num = Int32.Parse(i);
                producto.categoria.Add(db.categoriaSet.Single(c => c.Id == num));
            }

            if (Request.Files.Count > 0)
            {
                var file = Request.Files[0];

                if (file != null && file.ContentLength > 0)
                {
                    var fileName = producto.id + Path.GetExtension(file.FileName);

                    string ruta = "";

                    switch (producto.tipo)
                    {
                        case "cafe": ruta = "variedades-cafe"; break;
                        case "arte": ruta = "arte-cafe"; break;
                        case "bocado": ruta = "bodado"; break;
                    }

                    producto.imagen = fileName;
                    var path = Path.Combine(Server.MapPath("~/Content/img/" + ruta + "/"), fileName);
                    file.SaveAs(path);

                }
            }

            if (producto.imagen == null) producto.imagen = "#";

            if (ModelState.IsValid)
            {
                db.productoSet.Add(producto);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(producto);
        }

        public ActionResult Editar(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            producto producto = db.productoSet.Find(id);

            if (producto == null)
            {
                return HttpNotFound();
            }

            string[] selectedValues = new string[producto.categoria.Count];

            for (int i = 0; i < producto.categoria.Count; i++)
            {
                selectedValues[i] = producto.categoria.ElementAt(i).nombre.ToString();
            }

            List<categoria> categorias = db.categoriaSet.ToList<categoria>();
            categorias.Insert(0, new categoria { Id = -1, nombre = "Ninguna" });

            ViewBag.categorias = new MultiSelectList(categorias, "Id", "nombre", new string[] { "1" });
            ViewBag.selectedValues = selectedValues;

            return View(producto);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Editar([Bind(Include = "id,nombre,descripcion,precio,tipo,imagen")] producto producto, FormCollection form)
        {
            if (Request.Files.Count > 0)
            {
                var file = Request.Files[0];

                if (file != null && file.ContentLength > 0)
                {
                    var fileName = producto.id + Path.GetExtension(file.FileName);

                    string ruta = "";

                    switch (producto.tipo)
                    {
                        case "cafe": ruta = "variedades-cafe"; break;
                        case "arte": ruta = "arte-cafe"; break;
                        case "bocado": ruta = "bodado"; break;
                    }

                    producto.imagen = fileName;
                    var path = Path.Combine(Server.MapPath("~/Content/img/" + ruta + "/"), fileName);
                    file.SaveAs(path);

                }
            }

            if (ModelState.IsValid)
            {
                db.Entry(producto).State = EntityState.Modified;
                db.SaveChanges();

                if (form["Categorias"].Count() > 0)
                {
                    db.Database.ExecuteSqlCommand("DELETE FROM dbo.productocategoria WHERE producto_id = " + producto.id);

                    if (!form["Categorias"].Split(',')[0].Equals("-1"))
                    foreach (string i in form["Categorias"].Split(','))
                    {
                        db.Database.ExecuteSqlCommand("INSERT INTO dbo.productocategoria VALUES(" + producto.id + ", " + i + ")");
                    }
                }
                
                return RedirectToAction("Index");
            }

            return View(producto);
        }

        public ActionResult Eliminar(int id){
            db.Database.ExecuteSqlCommand("DELETE FROM dbo.productocategoria WHERE producto_id = " + id + ";");
            producto producto = db.productoSet.Find(id);
            db.productoSet.Remove(producto);
            db.SaveChanges();

            return RedirectToAction("Index");
        }
    }
}

Proyecto_CoffeeRun/Views/Producto/Crear.cshtml
@model Proyecto_CoffeeRun.Models.producto
@using Proyecto_CoffeeRun.Models;

@{
    ViewBag.Title = "Crear";
    Layout = "~/Views/Administrador/_AdmiMaster.cshtml";
}

@using (Html.BeginForm("Crear", "Producto", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()
    <div class="row row-form">
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })

        <div class="col-md-6">

            <div class="form-group">
                @Html.LabelFor(model => model.nombre, "Nombre")
                @Html.EditorFor(model => model.nombre, new { htmlAttributes = new { @class = "form-control" } })
            </div>
            <div class="form-group">
                @Html.LabelFor(model => model.descripcion, "Descripcion")
                @Html.TextAreaFor(model => model.descripcion, new { @class = "form-control" } )
            </div>
            <div class="form-group">
                @Html.LabelFor(model => model.precio, "Precio")
                @Html.EditorFor(model => model.precio, new { htmlAttributes = new { @class = "form-control" } })
            </div>
            <div class="form-group">
                @Html.LabelFor(model => model.tipo, "Tipo")
                @Html.DropDownListFor(model => model.tipo, new SelectList(new List<object>
                       {
                            new {value = "cafe", text = "Café"},
                            new {value = "bocado", text = "Bocado"},
                            new {value = "arte", text = "Arte"}
                       },
                       "value",
                       "text",
                       null),
                       htmlAttributes: new { @class = "form-control" })

            </div>
            <div class="form-group">
                @Html.LabelFor(model => model.categoria, "Categorias")
                @Html.ListBox("Categorias", ViewBag.categorias as MultiSelectList, htmlAttributes: new { @class = "form-control" })
            </div>
            <input type="submit" class="btn btn-default" value="Crear" />
            @Html.ActionLink("Atras", "Index", null, new { @class = "btn btn-default" });

        </div>
        <!-- Imagen -->
        <div class="col-md-6">
            <div class="form-group">
                <label>Imagen</label>
                @Html.LabelFor(model => model.imagen, "Imagen")
                <input type="file" name="file">
                <p class="help-block">Selecciona una imagen para el producto</p>
            </div>
        </div>
    </div>
}

Proyecto_CoffeeRun/Views/Producto/Editar.cshtml
@model Proyecto_CoffeeRun.Models.producto
@using Proyecto_CoffeeRun.Models;
@{
    ViewBag.Title = "Editar";
    Layout = "~/Views/Administrador/_AdmiMaster.cshtml";
}

@using (Html.BeginForm("Editar", "Producto", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()
    <div class="row row-form">
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.id)
        @Html.HiddenFor(model => model.imagen)

        <div class="col-md-6">

            <div class="form-group">
                @Html.LabelFor(model => model.nombre, "Nombre")
                @Html.EditorFor(model => model.nombre, new { htmlAttributes = new { @class = "form-control" } })
            </div>
            <div class="form-group">
                @Html.LabelFor(model => model.descripcion, "Descripcion")
                @Html.TextAreaFor(model => model.descripcion, new { @class = "form-control" } )
            </div>
            <div class="form-group">
                @Html.LabelFor(model => model.precio, "Precio")
                @Html.EditorFor(model => model.precio, new { htmlAttributes = new { @class = "form-control"}})
            </div>
            <div class="form-group">
                @Html.LabelFor(model => model.tipo, "Tipo")
                @Html.DropDownListFor(model => model.tipo, new SelectList(new List<object>
                       {
                            new {value = "cafe", text = "Café"},
                            new {value = "bocado", text = "Bocado"},
                            new {value = "arte", text = "Arte"}
                       },
                       "value",
                       "text",
                       Model.tipo),
                       htmlAttributes: new { @class = "form-control" })

            </div>
            <div class="form-group">
                @Html.LabelFor(model => model.categoria, "Categorias")
                @Html.ListBox("Categorias", ViewBag.categorias as MultiSelectList, htmlAttributes: new { @class = "form-control" })

                @foreach (string item in ViewBag.selectedValues)
                {
                    <kbd>@item</kbd>
                }
            </div>
            <input type="submit" class="btn btn-default" value="Editar" />
            @Html.ActionLink("Atras", "Index",null, new {@class = "btn btn-default" });

        </div>
        <!-- Imagen -->
        <div class="col-md-6">
            <div class="form-group">
                <label>Imagen</label>
                @*@Html.LabelFor(model => model.imagen, "Imagen")*@

                @if (Model.tipo.Equals("cafe"))
                {
                    <img src="~/Content/img/variedades-cafe/@Html.DisplayFor(model => model.imagen)" alt="Sin seleccionar" class="img-thumbnail center-block">
                }
                else if (Model.tipo.Equals("arte"))
                {
                    <img src="~/Content/img/arte-cafe/@Html.DisplayFor(model => model.imagen)" alt="Sin seleccionar" class="img-thumbnail center-block">
                }
                else
                {
                    <img src="~/Content/img/bocado/@Html.DisplayFor(model => model.imagen)" alt="Sin seleccionar" class="img-thumbnail center-block">
                }

                @*@Html.EditorFor(model => model.imagen, new { htmlAttributes = new { @type = "file" } })*@
                <input type="file" name="file">
                <p class="help-block">Selecciona una imagen para el producto</p>
            </div>
        </div>
    </div>
}

Proyecto_CoffeeRun/Views/Producto/Index.cshtml
@model PagedList.PagedList<Proyecto_CoffeeRun.Models.producto>
@using PagedList.Mvc;
@using Proyecto_CoffeeRun.Models;

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Administrador/_AdmiMaster.cshtml";
}

<div class="row">
    <div class="col-md-12">
        <!-- Action Buttons -->
        <div class="pull-left">
            <h3>Productos</h3>
        </div>
        <div class="pull-right">
            @Html.ActionLink("Crear", "Crear", null, htmlAttributes: new { @class = "btn btn-grey" })
        </div>
    </div>
</div>
<div class="row">
    <div class="col-md-12">
        <!-- Shopping Cart Items -->
        <table class="shopping-cart">
            <!-- Shopping Cart Item -->
            @foreach (var item in Model)
            {
                <tr>
                    <td class="image">
                        @if (item.tipo.Equals("cafe"))
                        {
                            <img src="~/Content/img/variedades-cafe/@Html.DisplayFor(model => item.imagen)" alt="Sin imagen">
                        }
                        else if (item.tipo.Equals("arte"))
                        {
                            <img src="~/Content/img/arte-cafe/@Html.DisplayFor(model => item.imagen)" alt="Sin imagen">
                        }
                        else
                        {
                            <img src="~/Content/img/bocado/@Html.DisplayFor(model => item.imagen)" alt="Sin imagen">
                        }
                    </td>
                    <!-- Shopping Cart Item Description & Features -->
                    <td>
                        <div class="cart-item-title">@Html.DisplayFor(modelItem => item.nombre)</div>
                        <div class="feature"><b>Descripción: </b>@Html.DisplayFor(modelItem => item.descripcion)</div>
                    </td>
                    <!-- Shopping Cart Item type -->
                    <td class="bg-primary type">
                        @Html.DisplayFor(modelItem => item.tipo)
                        <hr/>
                        @foreach (categoria i in @item.categoria)
                        {
                            @i.nombre<br/>
                        }
                    </td>
                    <!-- Shopping Cart Item Price -->
                    <td class="price">$ @Html.DisplayFor(modelItem => item.precio)</td>
                    <!-- Shopping Cart Item Actions -->

                    <td class="actions">
                        @Html.ActionLink(" ", "Editar", new { id = item.id }, htmlAttributes: new { @class = "glyphicon glyphicon-pencil" })
                        @Html.ActionLink(" ", "Eliminar", new { id = item.id }, htmlAttributes: new { @class = "glyphicon glyphicon-trash", onclick = "return confirm('¿Está seguro de eliminar el producto?');" })
                    </td>
                </tr>
            }

        </table>
        <!-- End Shopping Cart Items -->
        @Html.PagedListPager(Model, page => Url.Action("Index", new { page, pageSize = Model.PageSize, ViewBag.categoria }), new PagedListRenderOptions { ContainerDivClasses = new[] { "pagination-wrapper" }, UlElementClasses = new[] { "pagination pagination-lg" } })
    </div>
</div>

<div class="modal fade" id="modelEliminar" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <h4 class="modal-title" id="modalEliminarlLabel">Eliminar producto</h4>
            </div>
            <div class="modal-body">
                ¿Está seguro de que desea eliminar el producto seleccionado?
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">No</button>
                <button type="button" class="btn btn-primary">Si</button>
            </div>
        </div>
    </div>
</div>